### PR TITLE
Multithreading and version spoof to 4.20

### PR DESCRIPTION
**Pull request by playingoDEERUX**
Multithreading can be improved though, this is just some core...

### CODE REVIEW

**Comment by playingoDEERUX** [comment]
Tested 15min straight, no crashing.

**Comment by demonicbae** [comment]
Did you notice that you can update it until 5.99 instead of  4.20... Well mine's is good idea because it'll take more time!

**Comment by playingoDEERUX** [comment]
its the same thing... i dont know how high you can go but at 9.99 it weirdly autobanned me or maybe it was because of something else but the main thing here is multithreading

**Comment by demonicbae** [comment]
No,,, If you went like 6.50+ You would've get banned i think it's because growtopia detects the future or something like dat....

**Comment by playingoDEERUX** [comment]
anyways lol made this for fun, always working on my own projects got kinda boring so I hope this will do it.

**Comment by demonicbae** [comment]
Thanks
But there's a problem... i get many errors at the beginning when i see it i think i just mistake i don't know why!

**Comment by demonicbae** [comment]
Can you just copy and paste your server.cpp and paste it here? Thanks if you did!

**Comment by demonicbae** [comment]
Can you please give me your server.h and server.cpp? Because i didn't understand sorry for asking!

**Pull request closed without merging**
