### PR TITLE
wrench issue fix

### PR DESCRIPTION
**Pull request by SrMotion**
I put it in the wrong place so I'm sorry. Currently working smoothly.

### CODE REVIEW

**Comment by yEsPaP** [comment]
why did you add

        if (wrench == true) {
            if (content.find("set_default_color|`o") != -1) { // trash bug fix

?

**Comment by SrMotion** [comment]
blocks wrench dialog

**Comment by SrMotion** [comment]
ok now more evident and stable

**Comment by yEsPaP** [comment]
> blocks wrench dialog

you can make whole code in single ondialogrequest if...

```
            if (content.find("add_button|report_player|`wReport Player``|noflags|0|0|") != -1) {
                auto netid = content.substr(content.find("embed_data|netID|") + 17);
                if (gt::mode == "kick") {
                    g_server->send(false, "action|dialog_return\ndialog_name|popup\nnetID" + netid + "\nbuttonClicked|kick");
                    return true;
                }
                if (gt::mode == "pull") {
                    g_server->send(false, "action|dialog_return\ndialog_name|popup\nnetID" + netid + "\nbuttonClicked|pull");
                    return true;
                }
                if (gt::mode == "ban") {
                    g_server->send(false, "action|dialog_return\ndialog_name|popup\nnetID" + netid + "\nbuttonClicked|worldban");
                    return true;
                }
            }
```

heres how i do

**Comment by SrMotion** [comment]
You can try it works faster the way I do.

**Comment by SrMotion** [comment]
I already shared the ondialogrequest version on my youtube channel. That way it is more stable.

**Comment by yEsPaP** [comment]
> I already shared the ondialogrequest version on my youtube channel. That way it is more stable and fast.

not faster but ok

**Comment by SrMotion** [comment]
you can try :D

**Pull request merged**
