### PR TITLE
Spoof Version (No Need Change Version)

### PR DESCRIPTION
**Pull request by Cytee**
no more pull request for this

### CODE REVIEW

**Comment by hadessg** [comment]
thank god if this even works we wont have srmotion the god adding pr's every 4 mins

**Comment by qatroxx** [comment]
no way

**Comment by SrMotion** [comment]
😳

**Comment by ama6nen** [comment]
I'll merge for now but they might add some form of detection that just checks if one uses a version too high to check if one is using a proxy later

**Pull request merged**
