### PR TITLE
Add for sending raw packet

### PR DESCRIPTION
**Pull request by yEsPaP**
working

### CODE REVIEW

**Comment by yEsPaP** [comment]
why cant it merge tf

**Comment by qatroxx** [comment]
it already exists

**Comment by yEsPaP** [comment]
> it already exists

why are you after me

**Comment by qatroxx** [comment]
> > it already exists
> 
> why are you after me

because im skammer

**Comment by ama6nen** [comment]
void send(bool client, int32_t type, uint8_t* data, int32_t len);
This is already in it and equivalent

**Comment by yEsPaP** [comment]
> > > it already exists
> > 
> > 
> > why are you after me
> 
> because im skammer

i fking knew it.

youre a gypsy

**Comment by yEsPaP** [comment]
> void send(bool client, int32_t type, uint8_t* data, int32_t len);
> This is already in it and equivalent

i cant send punch (break) packet with it, no matter how i tried

**Comment by X0811** [comment]
this isnt working only visuals

**Pull request closed without merging**
